<div class="g-aside">
  <div class="hotel">
    <h1 class="hotel-name">{{title}}</h1>
    <p class="text-sm-center"><span class="user">操作员：张三</span></p>
    <ol class="nav">
      <li>
        <a href="" class="message" title="消息"><i class="iconfont-message"></i></a>
        <span>班次：早班</span>
      </li>
      <li>
        <span class="time float-sm-right">02:58</span>
        <span class="date">2017/11/25</span>
      </li>
    </ol>
  </div>
  {% include "./_asideMenu.swig" %}
</div>